---
title: "Wetland Loss Analysis"
format: html
editor: visual
---

## Bight Data Analysis - Ridgway's Rail

|             |
|-------------|
| Question #1 |
|             |

Team Members: Janeen, Audrey, Darien

### Load Packages

```{r}
library(tidyverse)
library(lme4)
library(lmerTest)
library(readxl)

```

### Import Data Files

```{r}
Rails <-read_excel("RidgwaysRailPBreedingPairs.xlsx", sheet=2)
index <-read_excel("RidgwaysRailPBreedingPairs.xlsx", sheet=1)
head(Rails)
as_tibble(Rails)
```

#### Cleaning

```{r}

Rails1 <-  Rails %>% select("Goleta Slough", "San Elijo Lagoon", "Huntington Beach Wetlands", "Upper Newport Bay", "Kendall-Frost Reserve", "Sweetwater Marsh", "Ventura River Mouth")
                               

Rails2 <- Rails1 |> rename(goletaslough = `Goleta Slough`, sanelijo = "San Elijo Lagoon", Huntington = "Huntington Beach Wetlands", NewportBay = "Upper Newport Bay", KFR = "Kendall-Frost Reserve", Sweetwater = "Sweetwater Marsh", Ventura = "Ventura River Mouth")



#add Tijuana Marsh NWR not recognizing it
```

## Data Analysis

#### Means of bare ground percentage at Low, Mid, and High of each site

```{r}

```
